# Update the age recipient below with your real public key(s).
# You can list multiple recipients if teams need different unlock codes.
creation_rules:
  - path_regex: bundles/.+\.sops\.ya?ml$
    age: age1akhct70nf0wjgxgyhqd4k2vw7d0tw5hgx04nrqlac5l3awn8zqes7fcuky
